language: java
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - TERM=dumb

after_success:
   - ./gradlew jacocoTestReport coveralls